"""add confirmed boolean column to users

Revision ID: 4f0d9924a728
Revises: 496982c3f7ab
Create Date: 2021-04-25 22:28:36.522785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0d9924a728'
down_revision = '496982c3f7ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'confirmed',
            sa.Boolean(),
            nullable=False,
            server_default="true"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
